# Generated by Django 6.0.5 on 2026-05-11 17:40

import django.db.models.deletion
import gateway.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('default_permission', models.CharField(choices=[('always_allow', 'always_allow'), ('requires_approval', 'requires_approval'), ('always_deny', 'always_deny')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('expired', 'expired')], default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=gateway.models._default_ticket_expiry)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.action')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='gateway.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_display', models.CharField(blank=True, max_length=200)),
                ('toolkit_slug', models.CharField(blank=True, max_length=64)),
                ('action_slug', models.CharField(blank=True, max_length=64)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('allowed', 'allowed'), ('denied', 'denied'), ('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('expired', 'expired')], max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.action')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='gateway.agent')),
                ('toolkit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gateway.toolkit')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='action',
            name='toolkit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='gateway.toolkit'),
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('always_allow', 'always_allow'), ('requires_approval', 'requires_approval'), ('always_deny', 'always_deny')], max_length=32)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.action')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='gateway.agent')),
            ],
            options={
                'unique_together': {('agent', 'action')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('toolkit', 'slug')},
        ),
    ]
