# Generated by Django 5.2.14 on 2026-05-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='agent_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
