# Generated by Django 5.2.14 on 2026-05-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_backfill_audit_agent_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='mcp_tool_name',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
